### ISSUE TITLE
"All types" in Bluetooth dialog makes it hard to set up new devices 

### ISSUE THREAD

**Issue by dandv** [linuxmint/blueberry#21]
_[Moved here from https://github.com/linuxmint/Cinnamon/issues/5620 because the project members there were too lazy to do do, say as a "thanks" for my time to file the bug report]_

Is it possible to be more specific about the detected Bluetooth devices? Maybe at least display the manufacturer based on the first three bytes of the MAC address?

Or display the MAC, even if cryptic, because the user might recognize one or two bytes from somewhere else where they might have seen it while pairing (e.g. in a car).

![image](https://cloud.githubusercontent.com/assets/33569/18191376/a6fc030a-707e-11e6-8b5f-bcff825fa558.png)

**Comment by dandv** [comment]
Sorry if I was misunderstood. As there still no README with the correct repos to file bugs in, I filed here.

If I received a bug report in my large project but in the wrong component, I'd thank the poster, tell them where to file it next time, *and* move it to the right component myself.

**Comment by JosephMcc** [comment]
Look, I understand where you're coming from and in a perfect world it might work that way. There are a couple of things you need to realize though. I, like most all of the Mint devs, do this in my free time. I have a full time job and a family. I woke up yesterday to around 50 of these that needed to be dealt with. I spent the entire time that I had before work trying to do my best to deal with those. I only really have two options here:

Do nothing. Don't bother with the tagging or attempting to keep things organized. This was kind of the approach we had been using and it led to some feedback from users saying they didn't bother posting bugs here because there was often no indication that anyone was even paying attention.

Because of that I went with the other option. Do the best I can in the time that I have. People seem to appreciate the fact of something even as small as having an issue tagged. They feel like taking the time to post an issue was productive. The only way I can do this though is to require a certain amount of help from all of you, the community, with moving your issues to the proper place. And to be frank, you are one of the only people who seem to take issue with that. Most people actually opt for just saying thanks for pointing them in the right direction and they handle it.

> As there still no README with the correct repos to file bugs in

I believe your README has now been merged but I can tell you from experience, not many people actually bother with looking for this type of thing. :)

**Comment by dandv** [comment]
Thanks Joseph! I really appreciate your help and will try my best to file bugs properly.

Also, glad the README was merged. Better than nothing :)

**Comment by clefebvre** [comment]
That's down to gnome-bluetooth's setting widget. We can't control that unfortunately.

**Comment by dandv** [comment]
@clefebvre: I there a ticket filed with gnome-bluetooth that I can follow?
