### ISSUE TITLE
rfkill permissions

### ISSUE THREAD

**Issue by memeplex** [linuxmint/blueberry#75]
I'm running blueberry outside of a desktop environment (the Arch Linux wiki describes it as "Linux Mint's spin-off of GNOME Bluetooth, which works in all desktop environments", I don't know how accurate this is but makes me think my use case is not out of question).

There is this toggle for disabling bluetooth, which I normally do using systemctl. It would be nice if it worked but it just fails miserably because it has no permission to run rfkill. Now, I guess I could modify sudoers so that my user can run rfkill without pass, but that's not nice. 

Why not calling rfkill using gksudo, pkexec or similar? I mean, something that requests the user to enter his/her pass. How is it that it works under Mint for a unpriviledged user?

**Comment by akspecs** [comment]
Strangely, I've only recently encountered this issue performing after a system upgrade.  Downgrading gnome-bluetooth to 3.32.0-1 from 3.32.1-1 prevents the 'rfkill: cannot open /dev/rfkill: Permission denied' when attempting to toggle the bluetooth on my end.  But now blueberry will freeze on certain occasions when toggling bluetooth.  Kind of curious what the issue here is, as I would prefer to continue to be able to toggle bluetooth without requiring root / sudo, as well as avoid messing up my permissions to workaround this issue.

**Comment by akspecs** [comment]
Strangely, I've only recently encountered this issue after performing a system upgrade. Downgrading gnome-bluetooth to 3.32.0-1 from 3.32.1-1 prevents the 'rfkill: cannot open /dev/rfkill: Permission denied' when attempting to toggle the bluetooth on my end. But now blueberry will freeze on certain occasions when toggling bluetooth. Kind of curious what the issue here is, as I would prefer to continue to be able to toggle bluetooth without requiring root / sudo, as well as avoid messing up my permissions to workaround this issue.

**Comment by erikdubois** [comment]
We can confirm that on ArcoLinux (Arch Linux based distro) we have discovered this issue as well. 

We are suggesting this solution as well to our users. At some point in the last updates we could no longer switch bluetooth on and off in the gui.

Launching blueberry-tray from the terminal revealed the fact that /dev/rfkill did not have permission.

The solution
`sudo usermod  -a -G rfkill $USER`

**Comment by shanmukhateja** [comment]
I searched for similar issues on the internet and I found these links from Arch Linux forum which talk about udev rules being changed for rfkill.

** Arch Linux forum: ** https://bbs.archlinux.org/viewtopic.php?id=245414

** Git commit for issue: ** https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gnome-bluetooth&id=0ad3b1690103ad919b200e6e2312f2c1c5b1a85b

I've checked the source code and I see that your `subprocess.Popen` calls for toggling Bluetooth do not check `stderr` or `stdout` streams and solely rely on `poll()` in `rfKillMagic.py`.

I wonder if we can use try-except block for capturing the error using `Popen.communicate()`, then complete the action using `gksu` or similar on failure.
